/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArRouteImport } from './routes/ar'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as MarkersIdRouteImport } from './routes/markers.$id'
import { Route as ToursIdRouteImport } from './routes/tours.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkersIdRoute = MarkersIdRouteImport.update({
  id: '/markers/$id',
  path: '/markers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIdRoute = ToursIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ToursRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ar': typeof ArRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/saved': typeof SavedRoute
  '/tours': typeof ToursRouteWithChildren
  '/markers/$id': typeof MarkersIdRoute
  '/tours/$id': typeof ToursIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ar': typeof ArRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/saved': typeof SavedRoute
  '/tours': typeof ToursRouteWithChildren
  '/markers/$id': typeof MarkersIdRoute
  '/tours/$id': typeof ToursIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ar': typeof ArRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/saved': typeof SavedRoute
  '/tours': typeof ToursRouteWithChildren
  '/markers/$id': typeof MarkersIdRoute
  '/tours/$id': typeof ToursIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ar'
    | '/explore'
    | '/login'
    | '/review'
    | '/saved'
    | '/tours'
    | '/markers/$id'
    | '/tours/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ar'
    | '/explore'
    | '/login'
    | '/review'
    | '/saved'
    | '/tours'
    | '/markers/$id'
    | '/tours/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/ar'
    | '/explore'
    | '/login'
    | '/review'
    | '/saved'
    | '/tours'
    | '/markers/$id'
    | '/tours/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArRoute: typeof ArRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  ReviewRoute: typeof ReviewRoute
  SavedRoute: typeof SavedRoute
  ToursRoute: typeof ToursRouteWithChildren
  MarkersIdRoute: typeof MarkersIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markers/$id': {
      id: '/markers/$id'
      path: '/markers/$id'
      fullPath: '/markers/$id'
      preLoaderRoute: typeof MarkersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$id': {
      id: '/tours/$id'
      path: '/$id'
      fullPath: '/tours/$id'
      preLoaderRoute: typeof ToursIdRouteImport
      parentRoute: typeof ToursRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ToursRouteChildren {
  ToursIdRoute: typeof ToursIdRoute
}

const ToursRouteChildren: ToursRouteChildren = {
  ToursIdRoute: ToursIdRoute,
}

const ToursRouteWithChildren = ToursRoute._addFileChildren(ToursRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArRoute: ArRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  ReviewRoute: ReviewRoute,
  SavedRoute: SavedRoute,
  ToursRoute: ToursRouteWithChildren,
  MarkersIdRoute: MarkersIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
